### ISSUE TITLE
Syntax error (ClassNotFoundException) compiling at (cljfx/coerce.clj:1:1)

### ISSUE THREAD

**Issue by lilactown** [jpmonettas/flow-storm-debugger#11] opened 2020-11-03 23:02 UTC
Attempting to run the `clj ,,,` snippet from the README to boot up the UI, does not show the UI and displays an error in my console that it cannot compile `cljfx/coerce.clj`.

This occurs on both openjdk 1.8 and openjdk 11

Environment:
macOS 10.15.6
openjdk version "11.0.9" 2020-10-20

Full report:

```
{:clojure.main/message
 "Syntax error (ClassNotFoundException) compiling at (cljfx/coerce.clj:1:1).\njavafx.event.EventHandler\n",
 :clojure.main/triage
 {:clojure.error/phase :compile-syntax-check,
  :clojure.error/line 1,
  :clojure.error/column 1,
  :clojure.error/source "coerce.clj",
  :clojure.error/path "cljfx/coerce.clj",
  :clojure.error/class java.lang.ClassNotFoundException,
  :clojure.error/cause "javafx.event.EventHandler"},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.Compiler$CompilerException,
    :message "Syntax error compiling at (cljfx/coerce.clj:1:1).",
    :data
    {:clojure.error/phase :compile-syntax-check,
     :clojure.error/line 1,
     :clojure.error/column 1,
     :clojure.error/source "cljfx/coerce.clj"},
    :at [clojure.lang.Compiler load "Compiler.java" 7648]}
   {:type java.lang.ClassNotFoundException,
    :message "javafx.event.EventHandler",
    :at
    [java.net.URLClassLoader findClass "URLClassLoader.java" 471]}],
  :trace
  [[java.net.URLClassLoader findClass "URLClassLoader.java" 471]
   [clojure.lang.DynamicClassLoader
    findClass
    "DynamicClassLoader.java"
    69]
   [java.lang.ClassLoader loadClass "ClassLoader.java" 589]
   [clojure.lang.DynamicClassLoader
    loadClass
    "DynamicClassLoader.java"
    77]
   [java.lang.ClassLoader loadClass "ClassLoader.java" 522]
   [java.lang.Class forName0 "Class.java" -2]
   [java.lang.Class forName "Class.java" 398]
   [clojure.lang.RT classForName "RT.java" 2211]
   [clojure.lang.RT classForNameNonLoading "RT.java" 2224]
   [cljfx.coerce$eval24191$loading__6721__auto____24192
    invoke
    "coerce.clj"
    1]
   [cljfx.coerce$eval24191 invokeStatic "coerce.clj" 1]
   [cljfx.coerce$eval24191 invoke "coerce.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7177]
   [clojure.lang.Compiler eval "Compiler.java" 7166]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.RT loadResourceScript "RT.java" 381]
   [clojure.lang.RT loadResourceScript "RT.java" 372]
   [clojure.lang.RT load "RT.java" 459]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6839 invoke "core.clj" 6126]
   [clojure.core$load invokeStatic "core.clj" 6125]
   [clojure.core$load doInvoke "core.clj" 6109]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5908]
   [clojure.core$load_one invoke "core.clj" 5903]
   [clojure.core$load_lib$fn__6780 invoke "core.clj" 5948]
   [clojure.core$load_lib invokeStatic "core.clj" 5947]
   [clojure.core$load_lib doInvoke "core.clj" 5928]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$load_libs invokeStatic "core.clj" 5985]
   [clojure.core$load_libs doInvoke "core.clj" 5969]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$require invokeStatic "core.clj" 6007]
   [clojure.core$require doInvoke "core.clj" 6007]
   [clojure.lang.RestFn invoke "RestFn.java" 482]
   [cljfx.lifecycle$eval24183$loading__6721__auto____24184
    invoke
    "lifecycle.clj"
    1]
   [cljfx.lifecycle$eval24183 invokeStatic "lifecycle.clj" 1]
   [cljfx.lifecycle$eval24183 invoke "lifecycle.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7177]
   [clojure.lang.Compiler eval "Compiler.java" 7166]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.RT loadResourceScript "RT.java" 381]
   [clojure.lang.RT loadResourceScript "RT.java" 372]
   [clojure.lang.RT load "RT.java" 459]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6839 invoke "core.clj" 6126]
   [clojure.core$load invokeStatic "core.clj" 6125]
   [clojure.core$load doInvoke "core.clj" 6109]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5908]
   [clojure.core$load_one invoke "core.clj" 5903]
   [clojure.core$load_lib$fn__6780 invoke "core.clj" 5948]
   [clojure.core$load_lib invokeStatic "core.clj" 5947]
   [clojure.core$load_lib doInvoke "core.clj" 5928]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$load_libs invokeStatic "core.clj" 5985]
   [clojure.core$load_libs doInvoke "core.clj" 5969]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$require invokeStatic "core.clj" 6007]
   [clojure.core$require doInvoke "core.clj" 6007]
   [clojure.lang.RestFn invoke "RestFn.java" 436]
   [cljfx.defaults$eval23816$loading__6721__auto____23817
    invoke
    "defaults.clj"
    1]
   [cljfx.defaults$eval23816 invokeStatic "defaults.clj" 1]
   [cljfx.defaults$eval23816 invoke "defaults.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7177]
   [clojure.lang.Compiler eval "Compiler.java" 7166]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.RT loadResourceScript "RT.java" 381]
   [clojure.lang.RT loadResourceScript "RT.java" 372]
   [clojure.lang.RT load "RT.java" 459]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6839 invoke "core.clj" 6126]
   [clojure.core$load invokeStatic "core.clj" 6125]
   [clojure.core$load doInvoke "core.clj" 6109]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5908]
   [clojure.core$load_one invoke "core.clj" 5903]
   [clojure.core$load_lib$fn__6780 invoke "core.clj" 5948]
   [clojure.core$load_lib invokeStatic "core.clj" 5947]
   [clojure.core$load_lib doInvoke "core.clj" 5928]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$load_libs invokeStatic "core.clj" 5985]
   [clojure.core$load_libs doInvoke "core.clj" 5969]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$require invokeStatic "core.clj" 6007]
   [clojure.core$require doInvoke "core.clj" 6007]
   [clojure.lang.RestFn invoke "RestFn.java" 619]
   [cljfx.api$eval23606$loading__6721__auto____23607
    invoke
    "api.clj"
    1]
   [cljfx.api$eval23606 invokeStatic "api.clj" 1]
   [cljfx.api$eval23606 invoke "api.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7177]
   [clojure.lang.Compiler eval "Compiler.java" 7166]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.RT loadResourceScript "RT.java" 381]
   [clojure.lang.RT loadResourceScript "RT.java" 372]
   [clojure.lang.RT load "RT.java" 459]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6839 invoke "core.clj" 6126]
   [clojure.core$load invokeStatic "core.clj" 6125]
   [clojure.core$load doInvoke "core.clj" 6109]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5908]
   [clojure.core$load_one invoke "core.clj" 5903]
   [clojure.core$load_lib$fn__6780 invoke "core.clj" 5948]
   [clojure.core$load_lib invokeStatic "core.clj" 5947]
   [clojure.core$load_lib doInvoke "core.clj" 5928]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$load_libs invokeStatic "core.clj" 5985]
   [clojure.core$load_libs doInvoke "core.clj" 5969]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$require invokeStatic "core.clj" 6007]
   [clojure.core$require doInvoke "core.clj" 6007]
   [clojure.lang.RestFn invoke "RestFn.java" 436]
   [flow_storm_debugger.ui.events$eval18444$loading__6721__auto____18445
    invoke
    "events.clj"
    1]
   [flow_storm_debugger.ui.events$eval18444
    invokeStatic
    "events.clj"
    1]
   [flow_storm_debugger.ui.events$eval18444 invoke "events.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7177]
   [clojure.lang.Compiler eval "Compiler.java" 7166]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.RT loadResourceScript "RT.java" 381]
   [clojure.lang.RT loadResourceScript "RT.java" 372]
   [clojure.lang.RT load "RT.java" 459]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6839 invoke "core.clj" 6126]
   [clojure.core$load invokeStatic "core.clj" 6125]
   [clojure.core$load doInvoke "core.clj" 6109]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5908]
   [clojure.core$load_one invoke "core.clj" 5903]
   [clojure.core$load_lib$fn__6780 invoke "core.clj" 5948]
   [clojure.core$load_lib invokeStatic "core.clj" 5947]
   [clojure.core$load_lib doInvoke "core.clj" 5928]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$load_libs invokeStatic "core.clj" 5985]
   [clojure.core$load_libs doInvoke "core.clj" 5969]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$require invokeStatic "core.clj" 6007]
   [clojure.core$require doInvoke "core.clj" 6007]
   [clojure.lang.RestFn invoke "RestFn.java" 2088]
   [flow_storm_debugger.server$eval138$loading__6721__auto____139
    invoke
    "server.clj"
    1]
   [flow_storm_debugger.server$eval138 invokeStatic "server.clj" 1]
   [flow_storm_debugger.server$eval138 invoke "server.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7177]
   [clojure.lang.Compiler eval "Compiler.java" 7166]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.RT loadResourceScript "RT.java" 381]
   [clojure.lang.RT loadResourceScript "RT.java" 372]
   [clojure.lang.RT load "RT.java" 459]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6839 invoke "core.clj" 6126]
   [clojure.core$load invokeStatic "core.clj" 6125]
   [clojure.core$load doInvoke "core.clj" 6109]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5908]
   [clojure.core$load_one invoke "core.clj" 5903]
   [clojure.core$load_lib$fn__6780 invoke "core.clj" 5948]
   [clojure.core$load_lib invokeStatic "core.clj" 5947]
   [clojure.core$load_lib doInvoke "core.clj" 5928]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$load_libs invokeStatic "core.clj" 5985]
   [clojure.core$load_libs doInvoke "core.clj" 5969]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$require invokeStatic "core.clj" 6007]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause "javafx.event.EventHandler",
  :phase :compile-syntax-check}}
```

**Comment by jpmonettas** [comment] 2020-11-04 00:00
Hmm interesting, looks like part of openjfx is missing.

What is your clojure version? 

Also can you paste the output of :
```
clj -Sdeps '{:deps {jpmonettas/flow-storm-debugger {:mvn/version "0.3.3"}}}' -Spath
```

In my case this command : 

```
$ clj -Sforce -Sdeps '{:deps {jpmonettas/flow-storm-debugger {:mvn/version "0.3.3"}}}' -Spath | tr ":" "\n" | grep jfx

/home/jmonetta/.m2/repository/cljfx/cljfx/1.7.10/cljfx-1.7.10.jar
/home/jmonetta/.m2/repository/cljfx/cljfx/1.7.10/cljfx-1.7.10-jdk11.jar
/home/jmonetta/.m2/repository/org/openjfx/javafx-media/14/javafx-media-14.jar
/home/jmonetta/.m2/repository/org/openjfx/javafx-web/14/javafx-web-14-linux.jar
/home/jmonetta/.m2/repository/org/openjfx/javafx-media/14/javafx-media-14-linux.jar
/home/jmonetta/.m2/repository/org/openjfx/javafx-controls/14/javafx-controls-14.jar
/home/jmonetta/.m2/repository/cljfx/css/1.1.0/css-1.1.0.jar
/home/jmonetta/.m2/repository/org/openjfx/javafx-controls/14/javafx-controls-14-linux.jar
/home/jmonetta/.m2/repository/org/openjfx/javafx-graphics/14/javafx-graphics-14-linux.jar
/home/jmonetta/.m2/repository/org/openjfx/javafx-graphics/14/javafx-graphics-14.jar
/home/jmonetta/.m2/repository/org/openjfx/javafx-base/14/javafx-base-14.jar
/home/jmonetta/.m2/repository/org/openjfx/javafx-base/14/javafx-base-14-linux.jar
/home/jmonetta/.m2/repository/org/openjfx/javafx-web/14/javafx-web-14.jar
```

And that missing class is inside: `/home/jmonetta/.m2/repository/org/openjfx/javafx-base/14/javafx-base-14-linux.jar`

Which is being installed by cljfx : 

```
clj -Sforce -Sdeps '{:deps {jpmonettas/flow-storm-debugger {:mvn/version "0.3.3"}}}' -Stree

org.clojure/clojure 1.10.1      
  org.clojure/core.specs.alpha 0.2.44
  org.clojure/spec.alpha 0.2.176
jpmonettas/flow-storm-debugger 0.3.3
  cljfx/cljfx 1.7.10     
    cljfx/cljfx$jdk11 1.7.10     
    org.openjfx/javafx-media 14           
      org.openjfx/javafx-media$linux 14 
    org.openjfx/javafx-controls 14       
      org.openjfx/javafx-controls$linux 14
    org.openjfx/javafx-graphics 14                                                            
      org.openjfx/javafx-graphics$linux 14                                                    
    org.openjfx/javafx-base 14                                                                
      org.openjfx/javafx-base$linux 14              <---------- javafx.event.EventHandler is here                                                        
    org.openjfx/javafx-web 14                
      org.openjfx/javafx-web$linux 14
...
...
```

I don't have a macosx box so I can't try there, but I'm interested in understanding how openjfx gets installed in different platforms. 

Thanks!

**Comment by lilactown** [comment] 2020-11-04 19:05
Okay this was fun.

Initially I ran the command:

```
$ clj -Sdeps '{:deps {jpmonettas/flow-storm-debugger {:mvn/version "0.3.3"}}}' -Spath | tr ":" "\n" | grep jfx
/Users/lilactown/.m2/repository/cljfx/cljfx/1.7.10/cljfx-1.7.10.jar
/Users/lilactown/.m2/repository/cljfx/cljfx/1.7.10/cljfx-1.7.10-jdk8.jar
/Users/lilactown/.m2/repository/cljfx/css/1.1.0/css-1.1.0.jar
```

Obviously missing JavaFX. Then, I ran `-Stree`, which _downloaded JavaFX_...

```
clj -Sforce -Sdeps '{:deps {jpmonettas/flow-storm-debugger {:mvn/version "0.3.3"}}}' -Stree
Downloading: org/kordamp/ikonli/ikonli-javafx/11.5.0/ikonli-javafx-11.5.0.pom from https://repo1.maven.org/maven2/
Downloading: org/kordamp/ikonli/ikonli-materialdesign-pack/11.5.0/ikonli-materialdesign-pack-11.5.0.pom from https://repo1.maven.org/maven2/
Downloading: org/openjfx/javafx-controls/14/javafx-controls-14.pom from https://repo1.maven.org/maven2/
Downloading: org/openjfx/javafx/14/javafx-14.pom from https://repo1.maven.org/maven2/
Downloading: org/openjfx/javafx-base/14/javafx-base-14.pom from https://repo1.maven.org/maven2/
Downloading: org/openjfx/javafx-graphics/14/javafx-graphics-14.pom from https://repo1.maven.org/maven2/
Downloading: org/openjfx/javafx-media/14/javafx-media-14.pom from https://repo1.maven.org/maven2/
Downloading: org/openjfx/javafx-web/14/javafx-web-14.pom from https://repo1.maven.org/maven2/
Downloading: org/kordamp/ikonli/ikonli-core/11.5.0/ikonli-core-11.5.0.pom from https://repo1.maven.org/maven2/
Downloading: org/openjfx/javafx-base/14/javafx-base-14-mac.jar from https://repo1.maven.org/maven2/
Downloading: cljfx/cljfx/1.7.10/cljfx-1.7.10-jdk11.jar from https://repo.clojars.org/
Downloading: org/openjfx/javafx-media/14/javafx-media-14.jar from https://repo1.maven.org/maven2/
Downloading: org/openjfx/javafx-controls/14/javafx-controls-14.jar from https://repo1.maven.org/maven2/
Downloading: org/kordamp/ikonli/ikonli-javafx/11.5.0/ikonli-javafx-11.5.0.jar from https://repo1.maven.org/maven2/
Downloading: org/openjfx/javafx-web/14/javafx-web-14-mac.jar from https://repo1.maven.org/maven2/
Downloading: org/kordamp/ikonli/ikonli-materialdesign-pack/11.5.0/ikonli-materialdesign-pack-11.5.0.jar from https://repo1.maven.org/maven2/
Downloading: org/openjfx/javafx-media/14/javafx-media-14-mac.jar from https://repo1.maven.org/maven2/
Downloading: org/openjfx/javafx-graphics/14/javafx-graphics-14.jar from https://repo1.maven.org/maven2/
Downloading: org/kordamp/ikonli/ikonli-core/11.5.0/ikonli-core-11.5.0.jar from https://repo1.maven.org/maven2/
Downloading: org/openjfx/javafx-base/14/javafx-base-14.jar from https://repo1.maven.org/maven2/
Downloading: org/openjfx/javafx-controls/14/javafx-controls-14-mac.jar from https://repo1.maven.org/maven2/
Downloading: org/openjfx/javafx-web/14/javafx-web-14.jar from https://repo1.maven.org/maven2/
Downloading: org/openjfx/javafx-graphics/14/javafx-graphics-14-mac.jar from https://repo1.maven.org/maven2/
org.clojure/clojure 1.10.1
  org.clojure/core.specs.alpha 0.2.44
  org.clojure/spec.alpha 0.2.176
jpmonettas/flow-storm-debugger 0.3.3
  cljfx/cljfx 1.7.10
    cljfx/cljfx$jdk11 1.7.10
    org.openjfx/javafx-media 14
      org.openjfx/javafx-media$mac 14
    org.openjfx/javafx-controls 14
      org.openjfx/javafx-controls$mac 14
    org.openjfx/javafx-graphics 14
      org.openjfx/javafx-graphics$mac 14
    org.openjfx/javafx-base 14
      org.openjfx/javafx-base$mac 14
    org.openjfx/javafx-web 14
      org.openjfx/javafx-web$mac 14
...
```

After which I ran `-Spath` again and saw all of the correct libs, and flow-storm starts correctly 😂 😭

**Comment by jpmonettas** [comment] 2020-11-04 20:33
Weirdness everywhere! Ok, happy it worked! Closing this then.

**Closed by jpmonettas** 2020-11-04 20:33 UTC

**Comment by KingMob** [comment] 2020-11-09 20:17
Glad to see this was resolved. FWIW, I can confirm the exact same behavior happened to me today. Running the commands above downloaded cljfx successfully, and now it works.
